// Code generated by MockGen. DO NOT EDIT.
// Source: acessors.go
//
// Generated by this command:
//
//	mockgen -source acessors.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateEngineAccessor is a mock of TemplateEngineAccessor interface.
type MockTemplateEngineAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateEngineAccessorMockRecorder
	isgomock struct{}
}

// MockTemplateEngineAccessorMockRecorder is the mock recorder for MockTemplateEngineAccessor.
type MockTemplateEngineAccessorMockRecorder struct {
	mock *MockTemplateEngineAccessor
}

// NewMockTemplateEngineAccessor creates a new mock instance.
func NewMockTemplateEngineAccessor(ctrl *gomock.Controller) *MockTemplateEngineAccessor {
	mock := &MockTemplateEngineAccessor{ctrl: ctrl}
	mock.recorder = &MockTemplateEngineAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateEngineAccessor) EXPECT() *MockTemplateEngineAccessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockTemplateEngineAccessor) Process(template string, ctxData map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", template, ctxData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockTemplateEngineAccessorMockRecorder) Process(template, ctxData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockTemplateEngineAccessor)(nil).Process), template, ctxData)
}
