package kwb

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"
)

func writeFixture(t testing.TB, root, path, content string) {
	t.Helper()
	path = filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
}

func testService(t testing.TB, root, index string, configure func(*Settings)) *Service {
	t.Helper()
	settings := NewSettings()
	settings.RootPath, settings.IndexPath = root, index
	if configure != nil {
		configure(settings)
	}
	service, err := NewService(settings)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := service.Close(); err != nil {
			t.Error(err)
		}
	})
	return service
}

func buildFixture(t testing.TB, service *Service, root string) BuildResult {
	t.Helper()
	report, err := service.BuildIndex(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	return report
}

func TestFilteringAndIncrementalUpdates(t *testing.T) {
	root := t.TempDir()
	index := filepath.Join(root, "search-index")
	for path, content := range map[string]string{
		".gitignore":      "ignored/\n*.secret\nnotes/*\n!notes/keep.md\n/anchored.md\n",
		"README.md":       "# Orchard\nnectarine planting\n",
		"service.go":      "package example\nfunc OriginalSymbol() {}\nfunc RemovedSymbol() {}\n",
		"ignored/skip.go": "package skip", "notes/skip.md": "skip", "notes/keep.md": "keep",
		"nested/.gitignore": "*.md\n!keep.md\n", "nested/skip.md": "skip", "nested/keep.md": "keep",
		"anchored.md": "skip", "other/anchored.md": "keep",
		".tools/artifact.md": "skip", ".build/artifact.go": "package skip",
		"custom/skip.md": "skip", "visible.secret": "skip",
		"extra.xyz": "custom extension", "Dockerfile": "FROM scratch", ".env": "APP_MODE=example",
		"generated.go": "// Code generated by generator. DO NOT EDIT.\npackage example\n",
		"go.sum":       "skip", "package-lock.json": "{}", "binary.md": "a\x00b", "huge.md": strings.Repeat("x", 1025),
	} {
		writeFixture(t, root, path, content)
	}
	service := testService(t, root, index, func(s *Settings) {
		s.ExtraExtensions = []string{".xyz"}
		s.ExcludeDirs = []string{"custom"}
		s.MaxFileSize = 1024
		s.BatchSize = 2
	})
	report := buildFixture(t, service, root)
	want := []string{
		".env",
		".gitignore",
		sourceIgnorePath,
		"Dockerfile",
		"README.md",
		"extra.xyz",
		"nested/.gitignore",
		"nested/keep.md",
		"notes/keep.md",
		"other/anchored.md",
		"service.go",
	}
	page, err := service.ListFiles(t.Context(), ListOptions{})
	if err != nil {
		t.Fatal(err)
	}
	var paths []string
	for _, file := range page.Files {
		paths = append(paths, file.Path)
	}
	if !slices.Equal(paths, want) {
		t.Fatalf("indexed paths = %v, want %v", paths, want)
	}
	if report.Indexed != len(want) || !report.Rebuilt {
		t.Fatalf("initial report: %+v", report)
	}
	generation := page.Generation
	// The index is inside the source root; repeated builds must not index its files.
	report = buildFixture(t, service, root)
	if report.Indexed != 0 || report.Deleted != 0 || report.Unchanged != len(want) || report.Rebuilt {
		t.Fatalf("no-op report: %+v", report)
	}
	stats, err := service.GetStats(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if stats.Generation != generation {
		t.Fatal("no-op build published a generation")
	}
	writeFixture(t, root, "service.go", "package example\nfunc ReplacementSymbol() {}\n")
	if err := os.Remove(filepath.Join(root, "README.md")); err != nil {
		t.Fatal(err)
	}
	writeFixture(t, root, "new.md", "# Fresh\napricot planting")
	report = buildFixture(t, service, root)
	if report.Indexed != 2 || report.Deleted != 1 || report.Unchanged != len(want)-2 {
		t.Fatalf("incremental report: %+v", report)
	}
	for _, word := range []string{"OriginalSymbol", "RemovedSymbol", "nectarine"} {
		result, err := service.Search(t.Context(), SearchOptions{
			Query: word,
		})
		if err != nil {
			t.Fatal(err)
		}
		if result.Total != 0 {
			t.Fatalf("stale content for %s: %+v", word, result)
		}
	}
	result, err := service.Search(t.Context(), SearchOptions{
		Query: "ReplacementSymbol",
	})
	if err != nil || result.Total != 1 {
		t.Fatalf("new content missing: %+v, %v", result, err)
	}
	// Hashes detect edits even when file size and modification time are unchanged.
	file := filepath.Join(root, "new.md")
	info, err := os.Stat(file)
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, root, "new.md", "# Fresh\npeaches planting")
	if err := os.Chtimes(file, info.ModTime(), info.ModTime()); err != nil {
		t.Fatal(err)
	}
	if report := buildFixture(t, service, root); report.Indexed != 1 {
		t.Fatalf("same-time edit ignored: %+v", report)
	}
	writeFixture(t, root, ".gitignore", "ignored/\n*.secret\nnotes/*\n!notes/keep.md\n/anchored.md\nnew.md\n")
	if report := buildFixture(t, service, root); report.Deleted != 1 {
		t.Fatalf("ignore change did not remove file: %+v", report)
	}
}

func TestChunkRankingAndRanges(t *testing.T) {
	root := t.TempDir()
	service := testService(t, root, filepath.Join(t.TempDir(), "index"), nil)
	writeFixture(
		t,
		root,
		"server.go",
		"package example\n\n// NewHTTPServer configures the listener.\nfunc NewHTTPServer() {}\n\nfunc Unrelated() {}\n",
	)
	writeFixture(
		t,
		root,
		"guide.md",
		"# Setup\nGeneral introduction.\n\n## HTTP server\nSet the listener port.\n\n## Storage\nConfigure the database.\n",
	)
	writeFixture(t, root, "config.json", "{\"http_server_port\": 8080}\n")
	writeFixture(t, root, "mentions.md", "# Notes\nNewHTTPServer is mentioned incidentally here.\n")
	buildFixture(t, service, root)
	for _, tc := range []struct {
		query, kind, language, path string
		line                        int
	}{
		{"NewHTTPServer", "", "", "server.go", 3},
		{"http server", "code", "go", "server.go", 3},
		{"HTTP server", "documentation", "", "guide.md", 4},
		{"8080", "config", "json", "config.json", 1},
		{"http_server_port", "config", "json", "config.json", 1},
	} {
		t.Run(tc.query+tc.kind, func(t *testing.T) {
			result, err := service.Search(
				t.Context(),
				SearchOptions{
					Query:    tc.query,
					Kind:     tc.kind,
					Language: tc.language,
				},
			)
			if err != nil {
				t.Fatal(err)
			}
			if len(result.Results) == 0 {
				t.Fatalf("no results for %q", tc.query)
			}
			hit := result.Results[0]
			if hit.Path != tc.path || hit.StartLine != tc.line {
				t.Fatalf("top hit: %+v", hit)
			}
			if strings.Contains(hit.Snippet, "<mark>") || len(hit.Snippet) > 2000 {
				t.Fatalf("invalid snippet: %q", hit.Snippet)
			}
			content, err := service.GetFile(t.Context(), hit.Path, hit.StartLine, hit.EndLine)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(content.Content, hit.Snippet) {
				t.Fatalf("snippet does not match source lines: %+v, %+v", hit, content)
			}
		})
	}
	result, err := service.Search(t.Context(), SearchOptions{
		Query:      "server",
		PathPrefix: "guide",
	})
	if err != nil || len(result.Results) != 1 || result.Results[0].Path != "guide.md" {
		t.Fatalf("prefix filter: %+v %v", result, err)
	}
	// Fenced headings stay inside their containing documentation section.
	docs := chunkFile("test.md", []byte("# Real\n```md\n# Example\n```\n## Next\nbody\n"))
	if len(docs) != 2 || docs[0].Title != "Real" || docs[1].Title != "Real > Next" {
		t.Fatalf("Markdown sections: %+v", docs)
	}
	long := chunkFile("long.md", []byte(strings.Repeat("long content\n", 300)))
	for _, doc := range long {
		if doc.EndLine-doc.StartLine+1 > maxChunkLines || len(doc.Content) > maxChunkBytes {
			t.Fatal("unbounded chunk")
		}
	}
	broken := chunkFile("broken.go", []byte("package example\nfunc Editing(\n"))
	if len(broken) == 0 {
		t.Fatal("incomplete Go source was discarded")
	}
}

func TestPaginationAndFileReading(t *testing.T) {
	root := t.TempDir()
	service := testService(t, root, filepath.Join(t.TempDir(), "index"), nil)
	for i := 0; i < 1051; i++ {
		writeFixture(t, root, fmt.Sprintf("docs/%04d.md", i), "# Orchard\napricot farming\n")
	}
	writeFixture(t, root, "long.md", strings.Repeat("orchard\n", 650))
	buildFixture(t, service, root)
	var paths []string
	for offset := 0; ; {
		page, err := service.ListFiles(t.Context(), ListOptions{
			Limit:  113,
			Offset: offset,
		})
		if err != nil {
			t.Fatal(err)
		}
		if page.Total != 1053 {
			t.Fatalf("total=%d", page.Total)
		}
		for _, file := range page.Files {
			paths = append(paths, file.Path)
		}
		if page.NextOffset == nil {
			break
		}
		offset = *page.NextOffset
	}
	if len(paths) != 1053 || len(slices.Compact(paths)) != 1053 {
		t.Fatal("pagination lost or duplicated files")
	}
	first, err := service.Search(t.Context(), SearchOptions{
		Query: "apricot",
		Limit: 17,
	})
	if err != nil || first.NextOffset == nil {
		t.Fatalf("first page: %+v %v", first, err)
	}
	second, err := service.Search(t.Context(), SearchOptions{
		Query:  "apricot",
		Limit:  17,
		Offset: *first.NextOffset,
	})
	if err != nil {
		t.Fatal(err)
	}
	if first.Total != 1051 || first.Results[0].Path == second.Results[0].Path {
		t.Fatal("invalid search pagination")
	}
	content, err := service.GetFile(t.Context(), "long.md", 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if content.StartLine != 1 || content.EndLine != 200 || content.NextStartLine == nil ||
		*content.NextStartLine != 201 ||
		content.TotalLines != 650 {
		t.Fatalf("range: %+v", content)
	}
	content, err = service.GetFile(t.Context(), "long.md", 640, 700)
	if err != nil || content.EndLine != 650 || content.NextStartLine != nil {
		t.Fatalf("last range: %+v %v", content, err)
	}
	for _, path := range []string{"../outside.md", filepath.Join(t.TempDir(), "outside.md")} {
		if _, err := service.GetFile(t.Context(), path, 1, 10); err == nil {
			t.Fatal("file outside root was accepted")
		}
	}
	if _, err := service.GetFile(t.Context(), "long.md", 1, 501); err == nil {
		t.Fatal("oversized range accepted")
	}
	if _, err := service.Search(t.Context(), SearchOptions{
		Query: "orchard",
		Limit: MaxSearchLimit + 1,
	}); err == nil {
		t.Fatal("oversized search accepted")
	}
	if _, err := service.ListFiles(t.Context(), ListOptions{
		Offset: -1,
	}); err == nil {
		t.Fatal("negative offset accepted")
	}
}

func TestFailedBuildKeepsPublishedIndex(t *testing.T) {
	root := t.TempDir()
	service := testService(t, root, filepath.Join(t.TempDir(), "index"), nil)
	writeFixture(t, root, "a.md", "original orchard")
	buildFixture(t, service, root)
	before, err := service.GetStats(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, root, "a.md", "replacement orchard")
	if err := os.MkdirAll(filepath.Join(root, "z", ".gitignore"), 0755); err != nil {
		t.Fatal(err)
	}
	if _, err := service.BuildIndex(t.Context(), root); err == nil {
		t.Fatal("failed scan reported success")
	}
	after, err := service.GetStats(t.Context())
	if err != nil || !reflect.DeepEqual(before, after) {
		t.Fatalf("failed build replaced index: %+v %+v %v", before, after, err)
	}
	result, err := service.Search(t.Context(), SearchOptions{
		Query: "original",
	})
	if err != nil || result.Total != 1 {
		t.Fatalf("old index damaged: %+v %v", result, err)
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	if _, err := service.BuildIndex(ctx, root); !errors.Is(err, context.Canceled) {
		t.Fatalf("build cancellation: %v", err)
	}
}

func TestConcurrentReadsUpdatesAndCancellation(t *testing.T) {
	root := t.TempDir()
	index := filepath.Join(t.TempDir(), "index")
	writer := testService(t, root, index, nil)
	reader := testService(t, root, index, nil)
	writeFixture(t, root, "doc.md", "shared orchard\n")
	buildFixture(t, writer, root)
	var wg sync.WaitGroup
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := 0; j < 20; j++ {
				result, err := reader.Search(t.Context(), SearchOptions{
					Query: "orchard",
				})
				if err != nil || result.Total != 1 {
					t.Errorf("concurrent search: %+v %v", result, err)
					return
				}
			}
		}()
	}
	for i := 0; i < 3; i++ {
		writeFixture(t, root, "doc.md", fmt.Sprintf("shared orchard revision %d\n", i))
		buildFixture(t, writer, root)
	}
	wg.Wait()
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	if _, err := reader.Search(ctx, SearchOptions{
		Query: "orchard",
	}); !errors.Is(err, context.Canceled) {
		t.Fatalf("search cancellation: %v", err)
	}
	if _, err := reader.ListFiles(ctx, ListOptions{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("list cancellation: %v", err)
	}
	if _, err := reader.GetFile(ctx, "doc.md", 1, 2); !errors.Is(err, context.Canceled) {
		t.Fatalf("read cancellation: %v", err)
	}
	fastTimeout := testService(t, root, index, func(s *Settings) { s.SearchTimeout = time.Nanosecond })
	if _, err := fastTimeout.Search(
		t.Context(),
		SearchOptions{
			Query: "orchard",
		},
	); !errors.Is(
		err,
		context.DeadlineExceeded,
	) {
		t.Fatalf("timeout was ignored: %v", err)
	}
}

func TestIndexBuildProcess(t *testing.T) {
	if os.Getenv("KWB_BUILD_HELPER") != "1" {
		t.Skip("subprocess helper")
	}
	service := testService(
		t,
		os.Getenv("KWB_BUILD_ROOT"),
		os.Getenv("KWB_BUILD_INDEX"),
		func(s *Settings) { s.Rebuild = os.Getenv("KWB_BUILD_FULL") == "1" },
	)
	buildFixture(t, service, os.Getenv("KWB_BUILD_ROOT"))
}

func TestCrossProcessPublication(t *testing.T) {
	root := t.TempDir()
	index := filepath.Join(t.TempDir(), "index")
	reader := testService(t, root, index, nil)
	writeFixture(t, root, "doc.md", "original orchard")
	buildFixture(t, reader, root)
	before, err := reader.GetStats(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	for _, full := range []string{"0", "1"} {
		writeFixture(t, root, "doc.md", "updated orchard "+full)
		ctx, cancel := context.WithTimeout(t.Context(), 15*time.Second)
		command := exec.CommandContext(ctx, os.Args[0], "-test.run=^TestIndexBuildProcess$")
		command.Env = append(
			os.Environ(),
			"KWB_BUILD_HELPER=1",
			"KWB_BUILD_ROOT="+root,
			"KWB_BUILD_INDEX="+index,
			"KWB_BUILD_FULL="+full,
		)
		output, err := command.CombinedOutput()
		cancel()
		if err != nil {
			t.Fatalf("building while reader is open: %v\n%s", err, output)
		}
		if _, err := os.Stat(filepath.Join(index, before.Generation)); err != nil {
			t.Fatalf("active reader generation removed: %v", err)
		}
		result, err := reader.Search(t.Context(), SearchOptions{
			Query: "updated",
		})
		if err != nil || result.Total != 1 || result.Generation == before.Generation {
			t.Fatalf("reader did not refresh: %+v %v", result, err)
		}
		before, err = reader.GetStats(t.Context())
		if err != nil {
			t.Fatal(err)
		}
	}
}

func TestBothIndexBackends(t *testing.T) {
	for _, backend := range []string{"scorch", "upsidedown"} {
		t.Run(backend, func(t *testing.T) {
			root := t.TempDir()
			service := testService(
				t,
				root,
				filepath.Join(t.TempDir(), "index"),
				func(s *Settings) { s.IndexType = backend },
			)
			writeFixture(t, root, "doc.md", "first orchard")
			buildFixture(t, service, root)
			writeFixture(t, root, "doc.md", "second orchard")
			if report := buildFixture(t, service, root); report.Indexed != 1 || report.Rebuilt {
				t.Fatalf("report: %+v", report)
			}
			result, err := service.Search(t.Context(), SearchOptions{
				Query: "second",
			})
			if err != nil || result.Total != 1 {
				t.Fatalf("backend search: %+v %v", result, err)
			}
		})
	}
}

func TestRecursiveIgnoreNegationAndRootReads(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, ".gitignore", "recursive/**\n!recursive/keep.md\n**/cache/\n\\#draft.md\n")
	for _, path := range []string{"recursive/keep.md", "recursive/skip.md", "nested/cache/skip.md", "#draft.md", "keep.md"} {
		writeFixture(t, root, path, "orchard")
	}
	service := testService(t, root, filepath.Join(t.TempDir(), "index"), nil)
	if file, err := service.GetFile(t.Context(), "keep.md", 0, 0); err != nil || file.Content != "orchard\n" {
		t.Fatalf("unindexed read: %+v %v", file, err)
	}
	buildFixture(t, service, root)
	files, err := service.ListFiles(t.Context(), ListOptions{})
	if err != nil {
		t.Fatal(err)
	}
	var paths []string
	for _, file := range files.Files {
		paths = append(paths, file.Path)
	}
	if !slices.Equal(paths, []string{".gitignore", sourceIgnorePath, "keep.md", "recursive/keep.md"}) {
		t.Fatalf("ignore semantics: %v", paths)
	}
	outside := filepath.Join(t.TempDir(), "outside.md")
	if err := os.WriteFile(outside, []byte("outside"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "outside.md")); err != nil {
		t.Fatal(err)
	}
	if _, err := service.GetFile(t.Context(), "outside.md", 0, 0); err == nil {
		t.Fatal("symlink escaped project root")
	}
	writeFixture(t, root, "large.md", strings.Repeat(strings.Repeat("a", 1000)+"\n", 200))
	file, err := service.GetFile(t.Context(), "large.md", 1, 200)
	if err != nil || len(file.Content) > MaxReadBytes || file.NextStartLine == nil {
		t.Fatalf("byte limit: %v", err)
	}
}

func TestIdentifiersWithNumericSuffixes(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "server42.go", "package example\nfunc NewHTTPServer42() {}\n")
	service := testService(t, root, filepath.Join(t.TempDir(), "index"), nil)
	buildFixture(t, service, root)
	for _, query := range []string{"NewHTTPServer42", "http server", "server42.go"} {
		result, err := service.Search(t.Context(), SearchOptions{
			Query: query,
		})
		if err != nil || result.Total == 0 || result.Results[0].Path != "server42.go" {
			t.Fatalf("query %q: %+v %v", query, result, err)
		}
	}
}

func TestDocumentationMetadataAndFrontmatter(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "specs/token-policy.md")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	source := "---\nid: REQ-001\ntitle: Token rotation\ncollection: requirements\nstatus: draft\nrelated: [ADR-001, auth]\n---\n\n# Refresh tokens\nRotate refresh tokens atomically.\n"
	if err := os.WriteFile(path, []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	settings := NewSettings()
	settings.RootPath = root
	settings.IndexPath = filepath.Join(t.TempDir(), "index")
	service, err := NewService(settings)
	if err != nil {
		t.Fatal(err)
	}
	defer service.Close() //nolint:errcheck
	if _, err = service.BuildIndex(t.Context(), root); err != nil {
		t.Fatal(err)
	}
	result, err := service.Search(t.Context(), SearchOptions{
		Query: "refresh tokens",
	})
	if err != nil || len(result.Results) != 1 {
		t.Fatalf("%+v %v", result, err)
	}
	hit := result.Results[0]
	if hit.DocumentID != "REQ-001" || hit.DocumentStatus != "draft" || hit.Collection != "requirements" ||
		len(hit.Related) != 2 ||
		hit.StartLine < 8 ||
		hit.Title != "Refresh tokens" ||
		hit.SourceHash == "" {
		t.Fatalf("metadata: %+v", hit)
	}
	stats, err := service.GetStats(t.Context())
	// One document chunk plus the automatically created project ignore file.
	if err != nil || stats.ChunkCount != 2 {
		t.Fatalf("front matter produced extra chunks: %+v %v", stats, err)
	}
}

func TestMissingReadLeaseDoesNotWriteOrChangeRoot(t *testing.T) {
	root := t.TempDir()
	settings := NewSettings()
	settings.RootPath = root
	settings.IndexPath = filepath.Join(t.TempDir(), "index")
	if err := os.WriteFile(filepath.Join(root, "file.md"), []byte("# Indexed project\n"), 0600); err != nil {
		t.Fatal(err)
	}
	service, err := NewService(settings)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = service.BuildIndex(t.Context(), root); err != nil {
		t.Fatal(err)
	}
	generation, err := service.index.(*indexManager).generation()
	if err != nil {
		t.Fatal(err)
	}
	if err = service.Close(); err != nil {
		t.Fatal(err)
	}
	lease := filepath.Join(settings.IndexPath, generation, "LEASE")
	if err = os.Remove(lease); err != nil {
		t.Fatal(err)
	}
	reader, err := NewService(settings)
	if err != nil {
		t.Fatal(err)
	}
	defer reader.Close() //nolint:errcheck
	if _, err = reader.GetStats(t.Context()); err == nil {
		t.Fatal("missing lease accepted")
	}
	if _, err = reader.GetFile(t.Context(), "file.md", 0, 0); err == nil {
		t.Fatal("corrupt index allowed unindexed fallback")
	}
	if _, err = os.Stat(lease); !os.IsNotExist(err) {
		t.Fatalf("reader created lease: %v", err)
	}
}
