package generator

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"path/filepath"
	"slices"
	"sort"

	"github.com/go42-dev/go42x/pkg/agentenv/config"
	"github.com/go42-dev/go42x/pkg/agentenv/generator/collector"
	"github.com/go42-dev/go42x/pkg/agentenv/generator/output"
	"github.com/go42-dev/go42x/pkg/agentenv/generator/provider"
)

const instructionsMarker = "<!-- Generated by go42x. Edit .go42x templates to change these instructions. -->"

type Generator struct {
	logger      *slog.Logger
	config      *config.Config
	providers   map[string]providerAccessor
	templateDir string
	outputDir   string
}

func NewGenerator(logger *slog.Logger, cfg *config.Config, templateDir, outputDir string) *Generator {
	// Resolve MCP paths on a private copy, preserving the caller's configuration.
	if cfg != nil {
		cfgCopy := *cfg
		cfgCopy.MCP = maps.Clone(cfg.MCP)
		cfg = &cfgCopy
	}

	g := &Generator{
		logger:      logger,
		config:      cfg,
		providers:   make(map[string]providerAccessor),
		templateDir: templateDir,
		outputDir:   outputDir,
	}

	g.registerProviders()

	return g
}

func (g *Generator) registerProviders() {
	templateEngine := newTemplateEngine(g.templateDir)

	g.providers[provider.Claude] = provider.NewClaudeProvider(
		g.logger.With("provider", provider.Claude),
		g.config, templateEngine, g.templateDir, g.outputDir)

	g.providers[provider.Codex] = provider.NewCodexProvider(
		g.logger.With("provider", provider.Codex),
		g.config, templateEngine, g.templateDir, g.outputDir)

	g.providers[provider.Gemini] = provider.NewGeminiProvider(
		g.logger.With("provider", provider.Gemini),
		g.config, templateEngine, g.templateDir, g.outputDir)

	g.providers[provider.Crush] = provider.NewCrushProvider(
		g.logger.With("provider", provider.Crush),
		g.config, templateEngine, g.templateDir, g.outputDir)

	g.providers[provider.Copilot] = provider.NewCopilotProvider(
		g.logger.With("provider", provider.Copilot),
		g.config, templateEngine, g.templateDir, g.outputDir)
}

func (g *Generator) Generate(ctx context.Context, clean bool) error {
	plan, err := g.Prepare(ctx, clean)
	if err != nil {
		return err
	}
	return plan.Apply()
}

// Prepare renders and validates all outputs without applying filesystem changes.
func (g *Generator) Prepare(ctx context.Context, clean bool) (*output.Plan, error) {
	if err := g.config.Validate(); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}

	for name, server := range g.config.MCP {
		if !server.Enabled || server.CWD == "" || filepath.IsAbs(server.CWD) {
			continue
		}
		cwd, err := filepath.Abs(filepath.Join(g.outputDir, server.CWD))
		if err != nil {
			return nil, fmt.Errorf("MCP server %s: failed to resolve cwd: %w", name, err)
		}
		server.CWD = cwd
		g.config.MCP[name] = server
	}

	g.logger.Info("Starting generation")

	tplCtx, err := g.buildTemplateContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to build context: %w", err)
	}

	plan := output.NewPlan(g.logger, g.outputDir)
	if err := g.prepareInstructions(plan, tplCtx.ToMap(), clean); err != nil {
		return nil, fmt.Errorf("failed to prepare shared instructions: %w", err)
	}

	var preparationErrors []error
	for _, name := range slices.Sorted(maps.Keys(g.config.Providers)) {
		if !g.config.ProviderEnabled(name) {
			continue
		}
		providerConfig := g.config.Providers[name]
		p, exists := g.providers[name]
		if !exists {
			preparationErrors = append(preparationErrors, fmt.Errorf("unknown provider %q", name))
			continue
		}
		ctxData := tplCtx.ToMap()
		ctxData["provider"] = name
		if err := p.Prepare(plan, ctxData, providerConfig); err != nil {
			g.logger.Error("Provider preparation failed", "provider", name, "error", err)
			preparationErrors = append(preparationErrors, fmt.Errorf("provider %s: %w", name, err))
		}
	}

	if err := errors.Join(preparationErrors...); err != nil {
		return nil, err
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	return plan, nil
}

func (g *Generator) buildTemplateContext(ctx context.Context) (*Context, error) {
	var (
		tplCtx = newContext(ctx)
	)

	collectors := []collectorAccessor{
		collector.NewGitCollector(g.outputDir),
		collector.NewProjectCollector(g.config),
		collector.NewEnvironmentCollector(g.config.EnvVars, g.outputDir),
		collector.NewGoCollector(g.outputDir, g.config.Context.GoEnv),
		collector.NewGitHubActionsCollector(),
	}

	sort.Slice(collectors, func(i, j int) bool {
		return collectors[i].Priority() < collectors[j].Priority()
	})

	collected := make(map[string]any)

	for _, c := range collectors {
		data, err := c.Collect(ctx)
		if len(data) > 0 {
			collected[c.Name()] = data
			if err != nil {
				g.logger.Warn("Collector returned partial data", "collector", c.Name(), "error", err)
			}
		} else if err != nil {
			g.logger.Error("Collector failed", "collector", c.Name(), "error", err)
		}
	}

	for k, v := range collected {
		tplCtx.Set(k, v)
	}

	servers := make(map[string]config.MCPServer)
	for name, server := range g.config.MCP {
		if server.Enabled {
			servers[name] = server
		}
	}

	tplCtx.Set("mcp", servers)

	return tplCtx, nil
}

func (g *Generator) prepareInstructions(plan *output.Plan, ctxData map[string]any, clean bool) error {
	content, err := newTemplateEngine(g.templateDir).Render(g.config.Context, ctxData)
	if err != nil {
		return err
	}

	outputs := map[string]string{provider.AgentsFile: content}
	for name, p := range g.providers {
		if !g.config.ProviderEnabled(name) {
			continue
		}
		if path := p.InstructionsFileName(); path != provider.AgentsFile {
			outputs[path] = "@" + provider.AgentsFile + "\n"
		}
	}

	for _, path := range slices.Sorted(maps.Keys(outputs)) {
		fullPath := filepath.Join(g.outputDir, path)
		if err := plan.Write(fullPath, []byte(instructionsMarker+"\n\n"+outputs[path]),
			output.Instructions, clean); err != nil {
			return fmt.Errorf("prepare instructions %s: %w", path, err)
		}
	}

	return nil
}
