// Code generated by MockGen. DO NOT EDIT.
// Source: accessors.go
//
// Generated by this command:
//
//	mockgen -source accessors.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kwb "github.com/go42-dev/go42x/pkg/kwb"
	gomock "go.uber.org/mock/gomock"
)

// MockindexAccessor is a mock of indexAccessor interface.
type MockindexAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockindexAccessorMockRecorder
	isgomock struct{}
}

// MockindexAccessorMockRecorder is the mock recorder for MockindexAccessor.
type MockindexAccessorMockRecorder struct {
	mock *MockindexAccessor
}

// NewMockindexAccessor creates a new mock instance.
func NewMockindexAccessor(ctrl *gomock.Controller) *MockindexAccessor {
	mock := &MockindexAccessor{ctrl: ctrl}
	mock.recorder = &MockindexAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockindexAccessor) EXPECT() *MockindexAccessorMockRecorder {
	return m.recorder
}

// BuildIndex mocks base method.
func (m *MockindexAccessor) BuildIndex(ctx context.Context, rootPath string) (kwb.BuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildIndex", ctx, rootPath)
	ret0, _ := ret[0].(kwb.BuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildIndex indicates an expected call of BuildIndex.
func (mr *MockindexAccessorMockRecorder) BuildIndex(ctx, rootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildIndex", reflect.TypeOf((*MockindexAccessor)(nil).BuildIndex), ctx, rootPath)
}

// CheckFreshness mocks base method.
func (m *MockindexAccessor) CheckFreshness(ctx context.Context) (*kwb.FreshnessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckFreshness", ctx)
	ret0, _ := ret[0].(*kwb.FreshnessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckFreshness indicates an expected call of CheckFreshness.
func (mr *MockindexAccessorMockRecorder) CheckFreshness(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFreshness", reflect.TypeOf((*MockindexAccessor)(nil).CheckFreshness), ctx)
}

// CloseIndex mocks base method.
func (m *MockindexAccessor) CloseIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseIndex indicates an expected call of CloseIndex.
func (mr *MockindexAccessorMockRecorder) CloseIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIndex", reflect.TypeOf((*MockindexAccessor)(nil).CloseIndex))
}

// GetFile mocks base method.
func (m *MockindexAccessor) GetFile(ctx context.Context, path string, startLine, endLine int) (*kwb.FileContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, path, startLine, endLine)
	ret0, _ := ret[0].(*kwb.FileContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockindexAccessorMockRecorder) GetFile(ctx, path, startLine, endLine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockindexAccessor)(nil).GetFile), ctx, path, startLine, endLine)
}

// GetStats mocks base method.
func (m *MockindexAccessor) GetStats(ctx context.Context) (*kwb.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*kwb.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockindexAccessorMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockindexAccessor)(nil).GetStats), ctx)
}

// ListFiles mocks base method.
func (m *MockindexAccessor) ListFiles(ctx context.Context, options kwb.ListOptions) (*kwb.FilesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, options)
	ret0, _ := ret[0].(*kwb.FilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockindexAccessorMockRecorder) ListFiles(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockindexAccessor)(nil).ListFiles), ctx, options)
}

// ProjectRoot mocks base method.
func (m *MockindexAccessor) ProjectRoot() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectRoot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectRoot indicates an expected call of ProjectRoot.
func (mr *MockindexAccessorMockRecorder) ProjectRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectRoot", reflect.TypeOf((*MockindexAccessor)(nil).ProjectRoot))
}

// Search mocks base method.
func (m *MockindexAccessor) Search(ctx context.Context, options kwb.SearchOptions) (*kwb.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, options)
	ret0, _ := ret[0].(*kwb.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockindexAccessorMockRecorder) Search(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockindexAccessor)(nil).Search), ctx, options)
}

// MockcatalogAccessor is a mock of catalogAccessor interface.
type MockcatalogAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockcatalogAccessorMockRecorder
	isgomock struct{}
}

// MockcatalogAccessorMockRecorder is the mock recorder for MockcatalogAccessor.
type MockcatalogAccessorMockRecorder struct {
	mock *MockcatalogAccessor
}

// NewMockcatalogAccessor creates a new mock instance.
func NewMockcatalogAccessor(ctrl *gomock.Controller) *MockcatalogAccessor {
	mock := &MockcatalogAccessor{ctrl: ctrl}
	mock.recorder = &MockcatalogAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcatalogAccessor) EXPECT() *MockcatalogAccessorMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockcatalogAccessor) Load(ctx context.Context, rootPath, entrypoint string) (*kwb.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, rootPath, entrypoint)
	ret0, _ := ret[0].(*kwb.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockcatalogAccessorMockRecorder) Load(ctx, rootPath, entrypoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockcatalogAccessor)(nil).Load), ctx, rootPath, entrypoint)
}
