// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source server.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	server "github.com/mark3labs/mcp-go/server"
	gomock "go.uber.org/mock/gomock"
)

// MockToolset is a mock of Toolset interface.
type MockToolset struct {
	ctrl     *gomock.Controller
	recorder *MockToolsetMockRecorder
	isgomock struct{}
}

// MockToolsetMockRecorder is the mock recorder for MockToolset.
type MockToolsetMockRecorder struct {
	mock *MockToolset
}

// NewMockToolset creates a new mock instance.
func NewMockToolset(ctrl *gomock.Controller) *MockToolset {
	mock := &MockToolset{ctrl: ctrl}
	mock.recorder = &MockToolsetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolset) EXPECT() *MockToolsetMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockToolset) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockToolsetMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockToolset)(nil).Name))
}

// Tools mocks base method.
func (m *MockToolset) Tools() []server.ServerTool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tools")
	ret0, _ := ret[0].([]server.ServerTool)
	return ret0
}

// Tools indicates an expected call of Tools.
func (mr *MockToolsetMockRecorder) Tools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tools", reflect.TypeOf((*MockToolset)(nil).Tools))
}
