// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source server.go -package mocks -destination mocks/mocks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	server "github.com/mark3labs/mcp-go/server"
	gomock "go.uber.org/mock/gomock"
)

// MocktoolsetAccessor is a mock of toolsetAccessor interface.
type MocktoolsetAccessor struct {
	ctrl     *gomock.Controller
	recorder *MocktoolsetAccessorMockRecorder
	isgomock struct{}
}

// MocktoolsetAccessorMockRecorder is the mock recorder for MocktoolsetAccessor.
type MocktoolsetAccessorMockRecorder struct {
	mock *MocktoolsetAccessor
}

// NewMocktoolsetAccessor creates a new mock instance.
func NewMocktoolsetAccessor(ctrl *gomock.Controller) *MocktoolsetAccessor {
	mock := &MocktoolsetAccessor{ctrl: ctrl}
	mock.recorder = &MocktoolsetAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktoolsetAccessor) EXPECT() *MocktoolsetAccessorMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MocktoolsetAccessor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MocktoolsetAccessorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MocktoolsetAccessor)(nil).Name))
}

// Tools mocks base method.
func (m *MocktoolsetAccessor) Tools() []server.ServerTool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tools")
	ret0, _ := ret[0].([]server.ServerTool)
	return ret0
}

// Tools indicates an expected call of Tools.
func (mr *MocktoolsetAccessorMockRecorder) Tools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tools", reflect.TypeOf((*MocktoolsetAccessor)(nil).Tools))
}
