package provider

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/go42-dev/go42x/pkg/agentenv/config"
	"github.com/go42-dev/go42x/pkg/agentenv/generator/output"
)

const (
	Antigravity          = "antigravity"
	AntigravityPluginDir = ".agents/plugins/project-tools"
)

// AntigravityPluginManifest identifies the generated workspace plugin.
// @see https://antigravity.google/docs/plugins
type AntigravityPluginManifest struct {
	Schema      string `json:"$schema"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// AntigravityMCPConfig represents the plugin's mcp_config.json.
type AntigravityMCPConfig struct {
	MCPServers map[string]AntigravityMCPServer `json:"mcpServers"`
}

// @see https://antigravity.google/docs/mcp
type AntigravityMCPServer struct {
	ServerURL string            `json:"serverUrl,omitempty"`
	Command   string            `json:"command,omitempty"`
	Args      []string          `json:"args,omitempty"`
	Env       map[string]string `json:"env,omitempty"`
	CWD       string            `json:"cwd,omitempty"`
	Headers   map[string]string `json:"headers,omitempty"`
}

type AntigravityProvider struct {
	*BaseProvider
}

func NewAntigravityProvider(
	logger *slog.Logger,
	cfg *config.Config,
	templateEngine TemplateEngineAccessor,
	templateDir, outputDir string,
) *AntigravityProvider {
	return &AntigravityProvider{
		BaseProvider: NewBaseProvider(logger, cfg, templateEngine, templateDir, outputDir),
	}
}

func (p *AntigravityProvider) Prepare(plan *output.Plan, _ map[string]any, _ config.Provider) error {
	if err := p.prepareConfigFiles(plan); err != nil {
		return fmt.Errorf("failed to prepare config files: %w", err)
	}
	return nil
}

func (p *AntigravityProvider) prepareConfigFiles(plan *output.Plan) error {
	pluginDir := filepath.Join(p.outputDir, AntigravityPluginDir)
	manifest := AntigravityPluginManifest{
		Schema:      "https://antigravity.google/schemas/v1/plugin.json",
		Name:        "project-tools",
		Description: "Project MCP tools generated by go42x.",
	}
	manifestPath := filepath.Join(pluginDir, "plugin.json")
	if err := p.prepareJSONFile(plan, manifestPath, manifest); err != nil {
		return fmt.Errorf("failed to prepare %s: %w", manifestPath, err)
	}

	servers := make(map[string]AntigravityMCPServer)
	for name, server := range p.config.MCP {
		if !server.Enabled {
			continue
		}
		var entry AntigravityMCPServer
		if server.Transport() == config.MCPServerTypeStdio {
			entry.Command = server.Command
			entry.Args = server.Args
			entry.Env = server.Env
			entry.CWD = server.CWD
		} else {
			entry.ServerURL = server.URL
			entry.Headers = server.Headers
		}
		servers[name] = entry
	}

	mcpPath := filepath.Join(pluginDir, "mcp_config.json")
	if err := p.prepareJSONFile(plan, mcpPath, AntigravityMCPConfig{MCPServers: servers}); err != nil {
		return fmt.Errorf("failed to prepare %s: %w", mcpPath, err)
	}

	return nil
}
