---

name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Setup Go'
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: 'Install Cosign'
        uses: sigstore/cosign-installer@v3
      - name: 'Install Syft'
        uses: anchore/sbom-action/download-syft@v0
      - name: 'Run GoReleaser'
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --config .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
